# Generated by Django 3.1.7 on 2021-03-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blob',
            options={'permissions': (('can_upload', 'Is allowd to upload blob'),)},
        ),
    ]
