# Generated by Django 3.1.7 on 2021-03-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210307_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blob',
            options={},
        ),
        migrations.AlterField(
            model_name='blob',
            name='filename',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
