# Generated by Django 3.1.7 on 2021-03-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210307_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blob',
            name='content_type',
            field=models.CharField(default='text/plain', max_length=128),
            preserve_default=False,
        ),
    ]
